version: '3'
services:
  web:
    build: .
    ports:
      - '1313:1313'
    volumes:
      - .:/blog
    command: hugo server --verbose --watch --buildFuture --buildDrafts --disableFastRender -D --bind 0.0.0.0
