name: Deploy blog
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@master

      - name: Pull theme
        uses: actions/checkout@v2
        with:
          repository: 'asurbernardo/amperage'
          ref: 'development'
          path: 'themes/amperage'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo -t amperage --gc --minify

      - name: Optimize AMP
        uses: asurbernardo/amp-optimizer-action@1.0.2
        with:
          root: './public'

      - name: Deploy script
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: bixamon/evl.pink
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
